###TESTE CONEXÃO
GET http://localhost:3000

###TESTE POST
POST http://localhost:3000
Content-Type: application/json

{
    "Nome": "Lucas Smaniotto",
    "Email": "lucassmaniottoo@gmail.com",
    "Curso": "TEC. Informática"
}

